name: freelenia
description: "Its a Work & payment Management App For Freelancers"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # 🔹 Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_messaging: ^16.0.2
  firebase_storage: ^13.0.2
  firebase_database: ^12.0.2
  encrypt: ^5.0.3
  crypto: ^3.0.3
  file_picker: ^8.1.2
  file_selector: ^1.0.3
  file_selector_android: ^0.5.1
  file_selector_ios: ^0.5.0
  # Media utils
  cached_network_image: ^3.3.1
  video_player: ^2.9.1
  video_thumbnail: ^0.5.3+2
  just_audio: ^0.9.37
  mime: ^1.0.5
  path_provider: ^2.1.3
  emoji_picker_flutter: ^3.0.0
  badges: ^2.0.3



  # 🔹 Notifications
  flutter_local_notifications: ^19.4.2
#  flutter_app_badger: ^1.5.0

  # 🔹 Other libs
  intl: ^0.20.2
  image_picker: ^1.0.7
  shared_preferences: ^2.2.3
  flutter_contacts: ^1.1.7
  permission_handler: ^12.0.1
  http: ^1.1.0
  googleapis_auth: ^2.0.0
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


#dependency_overrides:
#  flutter_app_badger:
#    git:
#      url: https://github.com/gedisa/flutter-app-badger
#      ref: master

icons_launcher:
  image_path: "assets/freelenia_splash.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/service_account.json
    - assets/default_avatar.png
    - assets/freelenia.png
    - assets/freelenia_splash.png
