// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTVYJw_4PEkO8Si66ODenhAnaNw5Gihz0',
    appId: '1:470110742427:web:1624197a989d150357233e',
    messagingSenderId: '470110742427',
    projectId: 'workspace-fd140',
    authDomain: 'workspace-fd140.firebaseapp.com',
    databaseURL: 'https://workspace-fd140-default-rtdb.firebaseio.com',
    storageBucket: 'workspace-fd140.firebasestorage.app',
    measurementId: 'G-TM02LZ7QRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTTkXYUgJPrtKI8dZLjbIaoKc4E-27hgg',
    appId: '1:470110742427:android:85ec50541ffddf6757233e',
    messagingSenderId: '470110742427',
    projectId: 'workspace-fd140',
    databaseURL: 'https://workspace-fd140-default-rtdb.firebaseio.com',
    storageBucket: 'workspace-fd140.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhKXZ_OAZ29b52ox0nvogoEZVxTvor4Q0',
    appId: '1:470110742427:ios:25503bb7699f84af57233e',
    messagingSenderId: '470110742427',
    projectId: 'workspace-fd140',
    databaseURL: 'https://workspace-fd140-default-rtdb.firebaseio.com',
    storageBucket: 'workspace-fd140.firebasestorage.app',
    iosClientId: '470110742427-h8edn2toi1k2de0tdphbkks4n12dunpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.freelenia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhKXZ_OAZ29b52ox0nvogoEZVxTvor4Q0',
    appId: '1:470110742427:ios:25503bb7699f84af57233e',
    messagingSenderId: '470110742427',
    projectId: 'workspace-fd140',
    databaseURL: 'https://workspace-fd140-default-rtdb.firebaseio.com',
    storageBucket: 'workspace-fd140.firebasestorage.app',
    iosClientId: '470110742427-h8edn2toi1k2de0tdphbkks4n12dunpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.freelenia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTVYJw_4PEkO8Si66ODenhAnaNw5Gihz0',
    appId: '1:470110742427:web:e6a19f15af8b80ba57233e',
    messagingSenderId: '470110742427',
    projectId: 'workspace-fd140',
    authDomain: 'workspace-fd140.firebaseapp.com',
    databaseURL: 'https://workspace-fd140-default-rtdb.firebaseio.com',
    storageBucket: 'workspace-fd140.firebasestorage.app',
    measurementId: 'G-8MP13838FQ',
  );
}
